#version: '3.8'
#
#services:
#  booking-service:
#    image: booking-service:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: booking-service
#    ports:
#      - "8091:8091"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Booking
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 19111993
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_RABBITMQ_PORT: 5672
#      SPRING_RABBITMQ_USERNAME: guest
#      SPRING_RABBITMQ_PASSWORD: guest
#      SPRING_CACHE_TYPE: redis
#      SPRING_DATA_REDIS_HOST: redis
#      SPRING_DATA_REDIS_PORT: 6379
#      SPRING_MAIL_HOST: smtp.gmail.com
#      SPRING_MAIL_PORT: 587
#      SPRING_MAIL_USERNAME: vadimkh17@gmail.com
#      SPRING_MAIL_PASSWORD: vhif kghh ijvs duhz
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: 5000
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 5000
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: 5000
#    depends_on:
#      - db
#      - rabbitmq
#      - redis
#
#  db:
#    image: postgres:13
#    container_name: postgres-db
#    restart: always
#    environment:
#      POSTGRES_DB: Booking
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 19111993
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#
#  redis:
#    image: redis:6
#    container_name: redis
#    ports:
#      - "6379:6379"
#
#volumes:
#  postgres-data:
#    driver: local


version: '3.8'

services:
  booking-service:
    image: booking-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8091:8091"
    environment:
      SPRING_APPLICATION_NAME: Booking
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 19111993
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_CACHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: vadimkh17@gmail.com
      SPRING_MAIL_PASSWORD: vhif kghh ijvs duhz
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: 5000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 5000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: 5000
    depends_on:
      - db
      - rabbitmq
      - redis

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: Booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19111993
    volumes:
      - /var/lib/postgresql/data
      - ./resources/init:/docker-entrypoint-db/migration
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
